version: '3.7'
services:
  db:
    image: mongo
    container_name : checklist-db
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=checklist
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password1
      - IMPORT_FROM_VOLUME=true
    ports:
      - '27017-27019:27017-27019'
    volumes: 
      - mongoData:/data/db 
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  checklist:
    build:
        context: ./
        dockerfile: ./Dockerfile
    ports:
        - '3000:3000' 
    depends_on:
        - db
volumes:
  mongoData:
    driver: local